workflows:
  ios-sideload-build:
    name: iOS Sideloading Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: default
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          flutter packages pub get
      - name: Build Flutter iOS App
        script: |
          cd frontend
          flutter build ios --no-codesign
      - name: Package Payload to IPA
        script: |
          cd frontend/build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          # -y preserves symlinks so iOS does not crash!
          zip -q -y -r sanzen_app.ipa Payload/
    artifacts:
      - frontend/build/ios/iphoneos/sanzen_app.ipa
